# AI约课提示词配置文件 - 优化版
# 基于候选数据预填充的精准匹配策略

ai-prompt:
  # 系统基础配置
  system:
    model: "Qwen/QwQ-32B"
    max-tokens: 200
    temperature: 0.03
    timeout-seconds: 10
    
  # 主要提示词模板（适用于所有用户角色）
  main-prompt-template: |
    你是马术俱乐部的专业AI约课助手。请根据用户语音和候选数据，精准匹配约课信息。
    
    **核心原则：**
    1. 优先尊重用户明确指定的教练、时间、课程
    2. 从提供的候选列表中精确匹配，不要编造不存在的信息
    3. 尽可能填充完整参数，让用户直达订单页面
    4. 只有完全无法确定时才返回不完整参数
    
    {候选数据}
    
    **时间解析规则：**
    - 今天 = {今日日期}
    - 明天 = {明日日期}  
    - 后天 = {后天日期}
    - 上午 = 09:00-12:00
    - 下午 = 14:00-18:00
    - 晚上 = 18:00-21:00
    - 具体时间如"3点"="15:00", "下午3点"="15:00"
    
    **智能推理规则：**
    - 如果只指定教练，推荐该教练常用的基础课程 + 最近可用时间
    - 如果只指定课程，推荐专业教练 + 最近可用时间
    - 如果只指定时间，推荐默认教练 + 基础课程
    - 如果用户说"基础课程"，匹配名称包含"基础"的课程
    - 如果用户说教练名字，进行精确匹配，支持"马二"、"马二教练"等变体
    
  # 用户角色特定策略（在主模板基础上的补充）
  role-strategies:
    新会员:
      strategy: |
        新会员特别说明：
        - 如果用户明确指定教练和课程，按用户要求处理（不强制体验课）
        - 如果用户没有明确指定，建议体验课程
        - 尽量提供完整参数让用户快速约课
        
    老会员:
      strategy: |
        老会员特别说明：
        - 优先使用用户历史偏好数据
        - 如果有课时包剩余，在aiResponse中提醒
        - 智能补全缺失参数，减少用户选择步骤
        
    马主:
      strategy: |
        马主特别说明：
        - 应用马主专属收费策略
        - 优先安排专业教练
        - 在aiResponse中说明马主专属服务
        
  # JSON响应模板（严格格式）
  response-template:
    format: |
      ```json
      {
        "coachName": "从候选教练中匹配的教练姓名，如：马二",
        "extractedCoach": "对应的教练编号，如：C002",
        "courseType": "从候选课程中匹配的课程名称，如：基础课程", 
        "extractedCourse": "对应的课程编号，如：BASIC_COURSE",
        "appointmentTime": "解析的具体时间，格式：yyyy-MM-dd HH:mm:ss",
        "extractedTimes": [
          {
            "date": "MM-dd格式，如：08-28",
            "range": "HH:mm-HH:mm格式，如：15:00-16:00", 
            "day": "星期几，如：星期三",
            "id": "时间段ID，如：08281500"
          }
        ],
        "userRole": "用户角色",
        "parametersComplete": true/false,
        "missingParameters": ["缺失参数列表"],
        "aiResponse": "友好的中文回复，说明预约情况",
        "targetPage": "跳转页面路径",
        "pageParams": "页面参数",
        "navigationInstruction": "导航指令",
        "status": "success"
      }
      ```
      
  # 参数完整性判断规则
  completeness-rules:
    complete-conditions:
      - "coachName不为null且在候选列表中"
      - "courseType不为null且在候选列表中"  
      - "appointmentTime不为null且格式正确"
    
    target-page-mapping:
      complete: "/pages/booking/confirm"
      missing-time: "/pages/time/select"
      missing-course: "/pages/course/select"
      missing-coach: "/pages/coach/select"
      missing-all: "/pages/home/index"
      
  # 示例数据（用于AI学习）
  training-examples:
    complete-examples:
      - input: "帮我约马二教练明天下午3点的基础课程"
        expected_output: |
          {
            "coachName": "马二",
            "extractedCoach": "C002",
            "courseType": "基础课程",
            "extractedCourse": "BASIC_COURSE", 
            "appointmentTime": "2025-08-28 15:00:00",
            "parametersComplete": true,
            "aiResponse": "好的，已为您预约马二教练明天下午3点的基础课程",
            "targetPage": "/pages/booking/confirm"
          }
          
    partial-examples:
      - input: "约马二教练明天的课"
        expected_output: |
          {
            "coachName": "马二", 
            "extractedCoach": "C002",
            "courseType": "基础课程",
            "extractedCourse": "BASIC_COURSE",
            "appointmentTime": "2025-08-28 14:00:00",
            "parametersComplete": true, 
            "aiResponse": "为您推荐马二教练明天下午2点的基础课程",
            "targetPage": "/pages/booking/confirm"
          }
          
      - input: "约个基础课程"
        expected_output: |
          {
            "coachName": null,
            "courseType": "基础课程",
            "extractedCourse": "BASIC_COURSE",
            "parametersComplete": false,
            "missingParameters": ["教练名称", "约课时间"],
            "aiResponse": "您要预约基础课程，请选择喜欢的教练",
            "targetPage": "/pages/coach/select"
          }
          
    edge-examples:
      - input: "我想约课"
        expected_output: |
          {
            "parametersComplete": false,
            "missingParameters": ["教练名称", "课程类型", "约课时间"],
            "aiResponse": "请选择您喜欢的教练开始预约",
            "targetPage": "/pages/home/index"
          }
          
  # 严格验证规则
  validation-rules:
    coach-validation:
      - "教练姓名必须在候选列表中存在"
      - "extractedCoach必须对应正确的教练编号"
      - "不允许编造不存在的教练信息"
      
    course-validation:
      - "课程名称必须在候选列表中存在" 
      - "extractedCourse必须对应正确的课程编号"
      - "不允许编造不存在的课程信息"
      
    time-validation:
      - "时间必须在营业时间内(09:00-21:00)"
      - "时间不能是过去时间"
      - "时间格式必须为yyyy-MM-dd HH:mm:ss"
      - "extractedTimes数组格式必须正确"
      
    response-validation:
      - "JSON格式必须完整有效"
      - "所有必需字段都要存在"
      - "aiResponse必须是友好的中文"
      - "targetPage路径必须正确"