package net.lab1024.sa.admin.module.business.order.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import net.lab1024.sa.base.module.support.datatracer.annoation.DataTracerFieldLabel;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * 订单主表实体
 *
 * @Author 1024创新实验室
 * @Date 2024-08-16
 * @Copyright <a href="https://1024lab.net">1024创新实验室</a>
 */
@Data
@TableName("m_order")
public class OrderEntity {

    @TableId(type = IdType.AUTO)
    private Long orderId;

    @DataTracerFieldLabel("订单号")
    private String orderNo;

    @DataTracerFieldLabel("俱乐部ID")
    private Long clubId;

    @DataTracerFieldLabel("会员ID")
    private Long memberId;

    @DataTracerFieldLabel("订单类型")
    private Integer orderType;

    @DataTracerFieldLabel("订单状态")
    private Integer orderStatus;

    @DataTracerFieldLabel("订单总金额")
    private BigDecimal totalAmount;

    @DataTracerFieldLabel("已支付金额")
    private BigDecimal paidAmount;

    @DataTracerFieldLabel("支付方式")
    private String paymentMethod;

    @DataTracerFieldLabel("支付时间")
    private LocalDateTime paymentTime;

    @DataTracerFieldLabel("订单备注")
    private String remark;

    @DataTracerFieldLabel("商品ID")
    private Long productId;

    @DataTracerFieldLabel("商品名称")
    private String productName;

    @DataTracerFieldLabel("商品类型")
    private Integer productType;

    @DataTracerFieldLabel("数量/课时数")
    private Integer quantity;

    @DataTracerFieldLabel("单价")
    private BigDecimal unitPrice;

    @DataTracerFieldLabel("默认教练ID")
    private Long coachId;

    @DataTracerFieldLabel("期望时间列表")
    private String preferredTimes;

    @DataTracerFieldLabel("支付过期时间")
    private LocalDateTime paymentExpireTime;

    @DataTracerFieldLabel("自动取消标志")
    private Integer autoCancelFlag;

    @DataTracerFieldLabel("订单子类型")
    private String orderSubType;

    @DataTracerFieldLabel("是否直接定价订单")
    private Integer isDirectPrice;

    @DataTracerFieldLabel("服务金额")
    private BigDecimal serviceAmount;

    @DataTracerFieldLabel("目标马匹ID")
    private Long targetHorseId;

    @DataTracerFieldLabel("关联预约ID")
    private Long relatedBookingId;

    @DataTracerFieldLabel("关联健康记录ID")
    private Long relatedHealthRecordId;

    @DataTracerFieldLabel("是否自动生成订单")
    private Integer autoGenerated;

    private String createBy;

    private LocalDateTime createTime;

    private String updateBy;

    private LocalDateTime updateTime;

    private Boolean isValid;

    private Boolean isDelete;
}